name: Lint check

on: [push, pull_request]

jobs:
  lint-clang-format:
    name: Lint with clang-format
    runs-on: ubuntu-latest
    if: ${{ false }}  # disable for now
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check code with clang-format
        uses: jidicula/clang-format-action@v4.5.0
        with:
          clang-format-version: "14"
  lint-black:
    name: Lint with black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install test dependencies
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            black
            isort
      - name: Check code with black
        run: black --check .
      - name: Check code with isort
        run: isort --profile black . --check-only
